bizforsale/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


admin.site.site_header = 'ACCOUNTS MONITOR'
admin.site.site_title = 'ACCOUNTS MONITOR'
admin.site.index_title = 'SITE ADMNISTRATION'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('company.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('businesses/', include('businesses.urls')),
    path('realestate/', include('realestate.urls')),
    path('leads/', include('leads.urls')),
    path('blog/', include('blog.urls'))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.blogView, name='blog'),
    path('<int:id>/', views.blogSingleView, name='blog_single'),
    path('comment', views.comments,  name='comment'),
    
]

realestate/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.commercialRealestate, name='realestate'),
    path('<int:id>/', views.commercialRealestateView, name='realestate_single'),
    path('contact', views.contactLeads, name='realestate_contact'),
    # path('comment', views.comments,  name='comment'),
    # path('search', views.search,  name='search')
]

blog/models.py
from django.db import models
#from tinymce.models import HTMLField

# Create your models here.
class Categories(models.Model):
    name = models.CharField(max_length=150)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name
    
class Tag(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name
    


class Blog(models.Model):
    author = models.CharField(max_length=150)
    title = models.CharField(max_length=150)
    thumbnail = models.ImageField(blank=True)
    content = models.TextField()
    tags = models.ManyToManyField(Tag, blank=True)
    categories = models.ForeignKey(Categories, blank=True, null=True, on_delete=models.SET_NULL)
    date = models.DateTimeField(auto_now_add=True)
    comments_count = models.IntegerField(null=True, blank=True)
    dateUpdated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    @property
    def imageURL(self):
        try:
            url = self.thumbnail.url
        except:
            url = ''
        return url
    @property
    def comment_count(self):
        try:
            comments_count = self.commnt_set.count()
        except:
            comments_count = 0
        return comments_count
    
class Comment(models.Model):
    name = models.CharField(max_length=150)
    email = models.EmailField(blank=True, null=True)
    message = models.TextField(max_length=1000)
    blog = models.ForeignKey(Blog, blank=True, null=True, on_delete=models.SET_NULL) 
    date = models.DateTimeField(auto_now_add=True)
    validated = models.BooleanField(default=True)
    replyId = models.CharField(max_length=150, blank=True, null=True)

    class Meta:
        ordering = ["-date"]

    def __str__(self):
        return self.name

businesses/models.py
from django.db import models
from company.models import User

# Create your models here.
class Industry(models.Model):
    name = models.CharField(max_length=150)
    def __str__(self):
        return self.name

class Categories(models.Model):
    name = models.CharField(max_length=150)
    def __str__(self):
        return self.name

class Businesse(models.Model):
    LEASED = 'leased'
    OWNED = 'owned'
    REALESTATE_CHOICES = [
        (OWNED ,"owned"), 
        (LEASED , "leased"),
        ]
    
    title = models.TextField(max_length=150)
    listed_by = models.ForeignKey(User, on_delete=models.CASCADE)
    industry = models.ForeignKey(Industry, on_delete=models.DO_NOTHING)
    category = models.ForeignKey(Categories, on_delete=models.DO_NOTHING)
    asking_price = models.CharField(max_length=150)
    business_name = models.CharField(max_length=150)
    business_owner =  models.CharField(max_length=150)
    business_photo = models.ImageField()
    cashflow = models.CharField(max_length=150)
    gross_annual_revenue = models.CharField(max_length=150)
    profits = models.CharField(max_length=150)

    country = models.CharField(max_length=150)
    county =models.CharField(max_length=150)
    location = models.CharField(max_length=150)
    address = models.CharField(max_length=150)
    realestate = models.CharField( max_length=7, choices=REALESTATE_CHOICES, default=LEASED)
    lease_expiration =models.DateField(blank=True, null=True)
    inventory = models.TextField(blank=True, null=True)
    number_of_employes = models.IntegerField(default=0)

    description = models.TextField(blank=True, null=True)
    competion = models.TextField(blank=True, null=True)
    support_and_training = models.TextField(blank=True, null=True)

    featured = models.BooleanField(default=False)
    closed_deal = models.BooleanField(default=False) 

    def __str__(self):
        return self.title

    @property
    def imageURL(self):
        try:
            url = self.business_photo.url
        except:
            url = ''
        return url

realestate/models.py
from django.db import models
from company.models import User

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name
    
class CommercialRealEState(models.Model):
    title = models.TextField(max_length=200)
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING)
    listed_by = models.ForeignKey(User, on_delete=models.CASCADE)
    asking_price = models.CharField(max_length=150)
    property_name = models.CharField(max_length=200)
    owner = models.TextField(max_length=300)
    total_rooms = models.CharField(max_length=100)
    current_occupied_rooms = models.CharField(max_length=100)
    average_montly_rental_income = models.CharField(max_length=100)
    property_description = models.TextField(blank=True, null=True)
    number_of_workers = models.IntegerField(default=0)
    building_photo = models.ImageField(blank=True, null=True)
    room_photos_1 = models.ImageField(blank=True, null=True)
    room_photos_2 = models.ImageField(blank=True, null=True)
    room_photos_3 = models.ImageField(blank=True, null=True)
    room_photos_4 = models.ImageField(blank=True, null=True)
    room_photos_5 = models.ImageField(blank=True, null=True)
    room_photos_6 = models.ImageField(blank=True, null=True)

    title_dead_exists = models.BooleanField(default=False) 
    property_square_area = models.CharField(max_length=100, blank=True, null=True)
    property_blue_prints = models.BooleanField(default=False)
    constructed_on = models.DateField(blank=True, null=True)

    property_disputes= models.BooleanField(default=False)
    disputes_description = models.TextField(blank=True, null=True)
    repair_needed = models.BooleanField(default=False)
    repair_description = models.TextField(blank=True, null=True)

    country = models.CharField(max_length=150)
    county =models.CharField(max_length=150)
    locationn = models.CharField(max_length=150)
    address = models.CharField(max_length=150)

    featured = models.BooleanField(default=False)
    closed_deal = models.BooleanField(default=False) 

    def __str__(self):
        return self.title
    @property
    def imageURL(self):
        try:
            url = self.building_photo.url
            
        except:
            url = ''

        return url 
    @property
    def photoURL(self):
        try:
            url = self.room_photos_1.url
            
        except:
            url = ''

        return url 
    
    @property
    def photo1URL(self):
        try:
            url = self.room_photos_2.url
            
        except:
            url = ''

        return url 
    
    @property
    def photo2URL(self):
        try:
            url = self.room_photos_3.url
            
        except:
            url = ''

        return url 
    @property
    def photo3URL(self):
        try:
            url = self.room_photos_4.url
            
        except:
            url = ''

        return url 
    @property
    def photo4URL(self):
        try:
            url = self.room_photos_5.url
            
        except:
            url = ''

        return url 
    @property
    def photo5URL(self):
        try:
            url = self.room_photos_6.url
            
        except:
            url = ''

        return url 
    

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import EmptyPage, Paginator
from . models import Blog, Tag, Categories, Comment
from company.models import  Information, SocialLink, OurContact
from django.db.models import  Q
from django.contrib import messages

# Create your views here.
def blogView(request):
    infos = Information.objects.order_by('id')[:1]
    links = SocialLink.objects.all()
    contacts_infos = OurContact.objects.order_by('id')[:1]
    blogs = Blog.objects.all().order_by('dateUpdated')
    paginator = Paginator(blogs, 5)
    page = request.GET.get('page')
    paged_blogs = paginator.get_page(page)
    posts = Blog.objects.order_by('-dateUpdated')[:5]
    tags = Tag.objects.all()
    categories = Categories.objects.all()
    category_id = request.GET.get('category', 0)
    tag_id = request.GET.get('tag', 0)
    query = request.GET.get('query')
    
    # paginator = Paginator(blogs, 2)
    # page = request.GET.get('page')
    # paged_blogs = paginator.get_page(page)
        # Keywords
    
    if query:
        blogs = blogs.filter(Q(content__icontains=query)| Q(title__icontains=query))
   
    if category_id :
        blogs = blogs.filter(categories__id=category_id )
    if tag_id :
        blogs = blogs.filter(tags__id=tag_id )
    
    
                     
    context = {
        'blogs' :paged_blogs,
        'infos' : infos,
        'links' : links,
        'contacts_infos':contacts_infos,
        'posts' : posts,
        'tags' : tags,
        'categories' : categories
    }
    return render(request, 'blog.html', context)

def blogSingleView(request, id):
    infos = Information.objects.order_by('id')[:1]
    links = SocialLink.objects.all()
    contacts_infos = OurContact.objects.order_by('id')[:1]
    blog = get_object_or_404(Blog, id=id)
    blogs = Blog.objects.filter(categories = blog.categories).exclude(id = blog.id)[:5]#reltaed blogs
    tags = Tag.objects.filter(blog__id = id)
    
    comments = blog.comment_set.all()
    context = {
        'blog': blog,
        'blogs' : blogs,
        'comments' : comments,
        'tags' : tags
    }
    return render(request, 'blog-single.html', context)


def comments(request):
    if request.method == 'POST':
        blog_id = request.POST['blog']
        blog = get_object_or_404(Blog, id=blog_id)
        name = request.POST['name']
        email = request.POST['email']
        message = request.POST['comment']

        comment = Comment(name=name, blog = blog, email=email, message=message)
        comment.save()
        messages.success(request, 'comment published successfuly!!')
        return redirect('http://www.localhost:8000/blog/' + blog_id  + '#comment' )

realestate/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import EmptyPage, Paginator
from . models import  CommercialRealEState, Category
from leads.models import Leads
from company.models import User
from company.models import  Information, SocialLink, OurContact
from django.db.models import  Q
from django.contrib import messages
from django.contrib.auth.decorators import login_required
# Create your views here.

def commercialRealestate(request):
    infos = Information.objects.order_by('id')[:1]
    links = SocialLink.objects.all()
    contacts_infos = OurContact.objects.order_by('id')[:1]
    realestates = CommercialRealEState.objects.filter(closed_deal=False).order_by('-id')
    paginator = Paginator(realestates, 6)
    page = request.GET.get('page')
    paged_realestates = paginator.get_page(page)
    bizs = CommercialRealEState.objects.order_by('-id')[:5]
    categories = Category.objects.all()

    category_id = request.GET.get('category', 0)
    query = request.GET.get('query')

    if query:
        realestates = realestates.filter(Q(property_description__icontains=query)| Q(title__icontains=query)|Q(locationn__icontains=query)|Q(county__icontains=query)|Q(address__icontains=query))
   
    if category_id :
        realestates = realestates.filter(category__id=category_id )
    context = {
        'infos':infos,
        'links':links,
        'contact_infos': contacts_infos,
        'paged_realestates':paged_realestates,
        'categories': categories,
        'bizs':bizs,
        'realestates': realestates

    }
    return render(request, 'realestate.html', context)

def commercialRealestateView(request, id):
    infos = Information.objects.order_by('id')[:1]
    links = SocialLink.objects.all()
    contacts_infos = OurContact.objects.order_by('id')[:1]
    user = request.user
    realestate = get_object_or_404(CommercialRealEState, id=id)
    relatedRealestates = CommercialRealEState.objects.filter(category = realestate.category).exclude(id = realestate.id)[:5]#reltaed blogs
    
    context = {
        'infos':infos,
        'links':links,
        'contact_infos': contacts_infos,
        'realestate': realestate,
        'user': user,
        'relatedRealestates' : relatedRealestates,
    }
    return render(request, 'realestate-single.html', context)

@login_required
def contactLeads(request):
    if request.method == 'POST':
        full_name = request.POST['full_name']
        phone_number = request.POST['phone_number']
        email = request.POST['email']
        message = request.POST['message']
        user = request.POST['target_user']
        biz = request.POST['business_intrested_in']
        target_user = get_object_or_404(User, id=user) 
        property_intrested_in = get_object_or_404(CommercialRealEState, id=biz) 

        contact = Leads(full_name=full_name, email=email, phone_number=phone_number, message=message, target_user=target_user, property_intrested_in=property_intrested_in )
        contact.save()
        messages.success(request, 'Thanks for reaching out, your message has been submitted succesfully')
        return redirect('/realestate/' + biz + '/')

templates/add_business.html
{% extends 'main.html' %}
{% load static %}


{% block title%} Add Business Listing {%endblock title%}
{%block content %}
<main>
   <!-- ======= Contact Section ======= -->
   <section id="contact" class="contact">

    <div class="container" data-aos="fade-up">

      <header class="section-header">
        <h2>Business</h2>
        <p>Add Your Business Listing</p>
        <div class=" sm-4 centre  mb-2 alert alert-primary alert-dismissible fade show" role="alert">
          Fill all fields with star (*) 
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    </header>
    
    <div class=" row gy-4 ">
      <div class="col-lg-12 ">
        <form action="{% url 'add_business' %}" method="post" enctype="multipart/form-data">
          {% if form.errors or form.non_field_errors %}
          <div class="col-12">
              {% for field in form %}
              <div class="alert alert-warning alert-dismissible fade show" role="alert">
              <p class="small mb-0" style="color: red;">{{ field.errors }}</p>
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
              {% endfor %}
          </div>
          {% endif %}
          {{form.non_field_errors}}
          {% csrf_token %}
              <div class="row gy-4">
                  <div class="row mb-3">
                      <label for="inputText" class="col-sm-2 col-form-label">Title *</label>
                      <div class="col-sm-10">
                          {{ form.title }}
                      </div>
                  </div>
                  <div class="row mb-3">
                      <label for="inputText" class="col-sm-2 col-form-label">Industry *</label>
                      <div class="col-sm-10">
                          {{ form.industry }}
                      </div>
                  </div>
                  <div class="row mb-3">
                    <label for="inputText" class="col-sm-2 col-form-label">Category *</label>
                    <div class="col-sm-10">
                        {{ form.category }}
                    </div>
                </div>
                  <div class="row mb-3">
                      <label for="inputText" class="col-sm-2 col-form-label">Asking Price*</label>
                      <div class="col-sm-10">
                          {{ form.asking_price }}  
                      </div>
                  </div>

                  <div class="row mb-3">
                      <label for="inputText" class="col-sm-2 col-form-label">Business Name *</label>
                      <div class="col-sm-10">
                          {{ form.business_name }}
                      </diV>
                  </div>
                  <div class="row mb-3">
                      <label for="inputText" class="col-sm-2 col-form-label">Business Owner *</label>
                      <div class="col-sm-10">
                          {{ form.business_owner }}
                      </div>
                  </div>
                  <div class="row mb-3">
                      <label for="inputText" class="col-sm-2 col-form-label">Business Photo *</label>
                      <div class="col-sm-10">
                          {{ form.business_photo }}
                      </div>
                  </div>
                  <div class="row mb-3">
                      <label for="inputText" class="col-sm-2 col-form-label">Cashflow *</label>
                      <div class="col-sm-10">
                          {{ form.cashflow }}
                      </div>
                  </div>
                  <div class="row mb-3">
                      <label for="inputText" class="col-sm-2 col-form-label">Gross Annual Revenue</label>
                      <div class="col-sm-10">
                          {{ form.gross_annual_revenue }}
                      </div>
                  </div>
                  <div class="row mb-3">
                      <label for="inputText" class="col-sm-2 col-form-label">Business Profits</label>
                      <div class="col-sm-10">
                          {{ form.profits }} 
                      </div> 
                  </div>
                  <div class="row mb-3">
                      <label for="inputText" class="col-sm-2 col-form-label">No. Of Employees</label>
                      <div class="col-sm-10">
                          {{ form.number_of_employes }}
                      </diV>
                  </div>

                  <div class="row mb-3">
                      <label for="inputText" class="col-sm-2 col-form-label">Realestate *</label>
                      <div class="col-sm-10">
                          {{ form.realestate }}
                      </div>
                  </div>
                  <div class="row mb-3">
                      <label for="inputText" class="col-sm-2 col-form-label">Lease Expiration</label>
                      <div class="col-sm-10">
                          {{ form.lease_expiration }}
                      </div>
                  </div>
                  <div class="row mb-3">
                      <label for="inputText" class="col-sm-2 col-form-label">Business Inventory</label>
                      <div class="col-sm-10">
                          {{ form.inventory }}
                      </div>
                  </div>
                  <div class="row mb-3">
                      <label for="inputText" class="col-sm-2 col-form-label">Business Description</label>
                      <div class="col-sm-10">
                          {{ form.description}}
                      </div>
                  </div>
                  <div class="row mb-3">
                      <label for="inputText" class="col-sm-2 col-form-label">Describe Competion Landscape</label>
                      <div class="col-sm-10">
                          {{ form.competion }}
                      </div>
                  </div>
                  <div class="row mb-3">
                      <label for="inputText" class="col-sm-2 col-form-label">Support And Training</label>
                      <div class="col-sm-10">
                          {{ form.support_and_training }}
                      </div>
                  </div>
                  <div class="row mb-3">
                      <label for="inputText" class="col-sm-2 col-form-label">Country *</label>
                      <div class="col-sm-10">
                          {{ form.country }}
                      </div>
                  </div>

                  <div class="row mb-3">
                      <label for="inputText" class="col-sm-2 col-form-label">County *</label>
                      <div class="col-sm-10">
                          {{ form.county }}
                      </div>
                  </div>
                  <div class="row mb-3">
                      <label for="inputText" class="col-sm-2 col-form-label">Location *</label>
                      <div class="col-sm-10">
                          {{ form.location }}
                      </div>
                  </div>
                  <div class="row mb-3">
                      <label for="inputText" class="col-sm-2 col-form-label">Address *</label>
                      <div class="col-sm-10">
                          {{ form.address }}
                      </div>
                  </div>

              <div class="col-md-12 text-center">
                  <button type="submit" id="submit" class="btn btn-primary">Add</button>
                </div>

                <div class="col-md-12 spinner-border text-center text-primary visually-hidden" id="loading" role="status">
                  <span class="visually-hidden">Loading...</span>
                </div>

          </div>
        </form>

      </div>

    </div>

    </div>

  </section><!-- End Contact Section --> 
</main>
{% comment %} <script type="text/javascript">
  
  document.getElementById('submit').addEventListener('click', function(e){
    document.getElementById('submit').classList.add("visually-hidden");
    document.getElementById('loading').classList.remove("visually-hidden");
    document.getElementById('loadingText').classList.remove("visually-hidden");
    })
</script> {% endcomment %}

{%endblock%}

templates/businesses.html
{% extends "main.html"%}
{% load static %}
{% block title%} Business For Sale  {% endblock title %}
{% block content %}

<main id="main" >

  <section class="breadcrumbs">
    <div class="container mt-2">

      <ol>
        <li><a href="{% url 'homepage' %}">Home</a></li>
        <li>Businesses</li>
      </ol>
      <h2>Businesses</h2>
    </div>
  </section><!-- End Breadcrumbs -->

  <!-- ======= Blog Section ======= -->
  <section id="blog" class="blog">
    <div class="container" data-aos="fade-up">

      <div class="row">
        {% if messages %}
            {% for message in messages %}

            <div class="alert alert-primary alert-dismissible fade show" role="alert">
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              <strong>
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                    Error : {{ message }}
                {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                    Success : {{ message }}
                {% else %}
                    {{ message.tags | title }}
                {% endif %}
                {{ message. }}
            </strong>
            </div>
                
            {% endfor %}
        {% endif %}
        <header class="section-header">
          <p>Find Your Next Business Opportunity</p>
        </header>
        

        <div class="col-lg-4">

          <div class="sidebar">

            <h3 class="sidebar-title">Search</h3>
            <div class="sidebar-item search-form">
              <form action="{% url 'biz' %}">
                <input type="text" name="query">
                <button type="submit"><i class="bi bi-search"></i></button>
              </form>
            </div><!-- End sidebar search formn-->
            <div class="flex" style="justify-content: space-between">
            <div class="sidebar-item categories dropdown "><a href="#"><span class="sidebar-title"> <i class="bi bi-folder"></i> Categories</span> <i class="bi bi-chevron-down"></i></a>
              <ul>
                {%for category in categories %}
                <li id = "category"><a href="{% url 'biz' %}?query={{ query }}&category={{category.id}}">{{category.name}} <span>({{category.businesse_set.count}})</span></a></li>
                {%endfor%}
              </ul>
            </div>
            <div class="sidebar-item categories dropdown"><a href="#"><span class="sidebar-title"> <i class="bi bi-grid"></i> Industries</span> <i class="bi bi-chevron-down"></i></a>
              <ul>
                {% for industry in industries %}
                <li id = "industry"><a href="{% url 'biz' %}?query={{ query }}&industry={{industry.id}}">{{ industry.name }} <span>({{industry.businesse_set.count}})</span></a></li>
                {% endfor %}
              </ul>
            </div><!-- End sidebar categories-->
            </div>
          </div><!-- End sidebar -->

        </div><!-- End blog sidebar -->

        <div class="col-lg-8 entries">
          {% for biz in businesses %}
          <article class="entry">
            
            <div class="entry-img">
              <img src="{{ biz.imageURL}}" alt="" class="img-fluid">
            </div>

            <h2 class="entry-title">
              <a href="{% url 'biz_single' biz.id %}">{{biz.title}}</a>
            </h2>
            <div class="entry-meta">
              <span class="post-date">{{biz.location}}, {{biz.county}}-{{biz.country}}</span>
            </div>

            <hr>
            <p>Asking Price : <strong>ksh{{biz.asking_price}}</strong></p>
            <p>Annual Revenue: <strong>ksh{{biz.gross_annual_revenue}}</strong></p>
            <p>Cashflow : <strong>ksh{{biz.cashflow}}</strong></p>
            <hr>
            <p>industry : {{biz.industry.name}}</p> 
            <p>category: {{biz.category.name}}</p>
            <hr>

            <div class="entry-content">
              <h6>
                    <strong>
                        Business Description
                    </strong>
                </h6>
                <div>
                {{biz.description|truncatechars:255}}
                </div>
              <div class="entry-footer">
                <i class="bi bi-folder"></i>
                <ul class="cats">
                  
                  <li><a href="{% url 'biz' %}?query={{ query }}&category={{biz.category.id}}" title="category">{{biz.category.name}}</a></li>
                  
                </ul>
              </div>
              <div class="read-more">
                <a href="{% url 'biz_single' biz.id %}">Find Out More</a>
              </div>
            </div>
          
          </article><!-- End blog entry -->
          {% endfor %}

          <!-- paginator -->
          <div class="row">
            <div class="col-md-12 ">
              {% if businesses.has_other_pages %}
                <ul class="pagination justify-content-center blog-pagination">
                  {% if businesses.has_previous %}
                    <a href="?page={{businesses.previous_page_number}}" class="page-link">&laquo;</a>
                  {% else %}
                    <li class="page-item disabled">
                      <a class="page-link">&laquo;</a>
                    </li>
                  {% endif %}
                  {% for i in businesses.paginator.page_range %}
                    {% if businesses.number == i %}
                      <li class="page-item active">
                        <a class="page-link">{{ i }}</a>
                      </li>
                    {% else %}
                      <li class="page-item">
                        <a href="?page={{i}}" class="page-link">{{ i }}</a>
                      </li>
                    {% endif %}
                  {% endfor %}
                  {% if businesses.has_next %}
                    <a href="?page={{ businesses.next_page_number }}" class="page-link">&raquo;</a>
                  {% else %}
                    <li class="page-item disabled">
                      <a class="page-link">&raquo;</a>
                    </li>
                  {% endif %}
                </ul>
              {% endif %}
            </div>
          </div>

        </div><!-- End blog entries list -->

      </div>

    </div>
  </section><!-- End Blog Section -->

</main><!-- End #main -->

{% endblock %}